jwt:
  token:
    key: H+MbQeThWmYq3t6w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B
    name: token
    expirationHours: 2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/internet_provider?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234